apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-frontend
  labels:
    app: agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-frontend
  template:
    metadata:
      labels:
        app: agent-frontend
    spec:
      containers:
        - name: agent-frontend
          image: 58.222.41.69:5000/agent-admin:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agent-frontend-svc
spec:
  selector:
    app: agent-frontend
  ports:
    - name: agent-frontend-svc
      protocol: TCP
      port: 80
      targetPort: 80
